package uy.com.group05.baascore.sl.services.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import uy.com.group05.baascore.sl.services.soap.PushChannelServices;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-09T00:10:06.530-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PushServices", 
                  wsdlLocation = "http://baas-gonzalomelov.rhcloud.com/baas-core/PushServices?wsdl",
                  targetNamespace = "http://impl.services.sl.baascore.group05.com.uy/") 
public class PushServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.services.sl.baascore.group05.com.uy/", "PushServices");
    public final static QName PushServicesPort = new QName("http://impl.services.sl.baascore.group05.com.uy/", "PushServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://baas-gonzalomelov.rhcloud.com/baas-core/PushServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PushServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://baas-gonzalomelov.rhcloud.com/baas-core/PushServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PushServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PushServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PushServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PushServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PushServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PushServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PushChannelServices
     */
    @WebEndpoint(name = "PushServicesPort")
    public PushChannelServices getPushServicesPort() {
        return super.getPort(PushServicesPort, PushChannelServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PushChannelServices
     */
    @WebEndpoint(name = "PushServicesPort")
    public PushChannelServices getPushServicesPort(WebServiceFeature... features) {
        return super.getPort(PushServicesPort, PushChannelServices.class, features);
    }

}
