
package uy.com.group05.baascore.sl.services.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import uy.com.group05.baascore.sl.services.impl.ApplicationServices;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-03T12:30:40.275-02:00
 * Generated source version: 2.4.6
 * 
 */
public final class ApplicationServices_ApplicationServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.services.sl.baascore.group05.com.uy/", "ApplicationServices");

    private ApplicationServices_ApplicationServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ApplicationServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ApplicationServices ss = new ApplicationServices(wsdlURL, SERVICE_NAME);
        ApplicationServices port = ss.getApplicationServicesPort();  
        
        {
        System.out.println("Invoking addPushChannelToApplication...");
        long _addPushChannelToApplication_idApp = 2541249284208797576l;
        java.lang.String _addPushChannelToApplication_nombreCanal = "_addPushChannelToApplication_nombreCanal876807721";
        try {
            long _addPushChannelToApplication__return = port.addPushChannelToApplication(_addPushChannelToApplication_idApp, _addPushChannelToApplication_nombreCanal);
            System.out.println("addPushChannelToApplication.result=" + _addPushChannelToApplication__return);

        } catch (PushChanAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createApplication...");
        long _createApplication_idUser = 8586537657244845963l;
        java.lang.String _createApplication_nombreApp = "_createApplication_nombreApp452950833";
        java.util.List<java.lang.String> _createApplication_rolStr = new java.util.ArrayList<java.lang.String>();
        java.lang.String _createApplication_rolStrVal1 = "_createApplication_rolStrVal-1465235704";
        _createApplication_rolStr.add(_createApplication_rolStrVal1);
        java.util.List<java.lang.String> _createApplication_entidadStr = new java.util.ArrayList<java.lang.String>();
        java.lang.String _createApplication_entidadStrVal1 = "_createApplication_entidadStrVal401836565";
        _createApplication_entidadStr.add(_createApplication_entidadStrVal1);
        try {
            long _createApplication__return = port.createApplication(_createApplication_idUser, _createApplication_nombreApp, _createApplication_rolStr, _createApplication_entidadStr);
            System.out.println("createApplication.result=" + _createApplication__return);

        } catch (NombreAppAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: NombreAppAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (MongoDBAlreadyExistsException_Exception e) { 
            System.out.println("Expected exception: MongoDBAlreadyExistsException has occurred.");
            System.out.println(e.toString());
        } catch (EntityCollectionAlreadyExistsException_Exception e) { 
            System.out.println("Expected exception: EntityCollectionAlreadyExistsException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidNameException_Exception e) { 
            System.out.println("Expected exception: InvalidNameException has occurred.");
            System.out.println(e.toString());
        } catch (UserNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: UserNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking editApplication...");
        java.lang.String _editApplication_nombreApp = "_editApplication_nombreApp-799349009";
        java.util.List<java.lang.String> _editApplication_rolStr = new java.util.ArrayList<java.lang.String>();
        java.lang.String _editApplication_rolStrVal1 = "_editApplication_rolStrVal515012717";
        _editApplication_rolStr.add(_editApplication_rolStrVal1);
        java.util.List<java.lang.String> _editApplication_entidadStr = new java.util.ArrayList<java.lang.String>();
        java.lang.String _editApplication_entidadStrVal1 = "_editApplication_entidadStrVal1510452971";
        _editApplication_entidadStr.add(_editApplication_entidadStrVal1);
        try {
            long _editApplication__return = port.editApplication(_editApplication_nombreApp, _editApplication_rolStr, _editApplication_entidadStr);
            System.out.println("editApplication.result=" + _editApplication__return);

        } catch (MongoDBAlreadyExistsException_Exception e) { 
            System.out.println("Expected exception: MongoDBAlreadyExistsException has occurred.");
            System.out.println(e.toString());
        } catch (EntityCollectionAlreadyExistsException_Exception e) { 
            System.out.println("Expected exception: EntityCollectionAlreadyExistsException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking removePushChannelFromApplication...");
        long _removePushChannelFromApplication_idApp = -3178075817076628374l;
        long _removePushChannelFromApplication_idCanal = -4890988610184934972l;
        try {
            long _removePushChannelFromApplication__return = port.removePushChannelFromApplication(_removePushChannelFromApplication_idApp, _removePushChannelFromApplication_idCanal);
            System.out.println("removePushChannelFromApplication.result=" + _removePushChannelFromApplication__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listApplications...");
        long _listApplications_idUser = -2836436790445727011l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO> _listApplications__return = port.listApplications(_listApplications_idUser);
            System.out.println("listApplications.result=" + _listApplications__return);

        } catch (UserNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: UserNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPermissionsForEntity...");
        long _getPermissionsForEntity_appId = -3851811082034974880l;
        long _getPermissionsForEntity_entityId = 7598050408054480324l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _getPermissionsForEntity__return = port.getPermissionsForEntity(_getPermissionsForEntity_appId, _getPermissionsForEntity_entityId);
            System.out.println("getPermissionsForEntity.result=" + _getPermissionsForEntity__return);

        } catch (EntityCollectionNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityCollectionNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPushChannelsApplication...");
        long _getPushChannelsApplication_idApp = -7929987482332979273l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _getPushChannelsApplication__return = port.getPushChannelsApplication(_getPushChannelsApplication_idApp);
            System.out.println("getPushChannelsApplication.result=" + _getPushChannelsApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking editRoleApplication...");
        long _editRoleApplication_idApp = -3986072711175139414l;
        long _editRoleApplication_idUser = -830395293654298490l;
        java.lang.String _editRoleApplication_nomRole = "_editRoleApplication_nomRole-1651167906";
        try {
            long _editRoleApplication__return = port.editRoleApplication(_editRoleApplication_idApp, _editRoleApplication_idUser, _editRoleApplication_nomRole);
            System.out.println("editRoleApplication.result=" + _editRoleApplication__return);

        } catch (RoleAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: RoleAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidNameException_Exception e) { 
            System.out.println("Expected exception: InvalidNameException has occurred.");
            System.out.println(e.toString());
        } catch (UserCantAccessAppException_Exception e) { 
            System.out.println("Expected exception: UserCantAccessAppException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEntitiesApplication...");
        long _getEntitiesApplication_idApp = -6348232840305364762l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _getEntitiesApplication__return = port.getEntitiesApplication(_getEntitiesApplication_idApp);
            System.out.println("getEntitiesApplication.result=" + _getEntitiesApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientsApplication...");
        long _getClientsApplication_idApp = -8625448701393466576l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _getClientsApplication__return = port.getClientsApplication(_getClientsApplication_idApp);
            System.out.println("getClientsApplication.result=" + _getClientsApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRolesApplication...");
        long _getRolesApplication_idApp = 1586814522289817141l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _getRolesApplication__return = port.getRolesApplication(_getRolesApplication_idApp);
            System.out.println("getRolesApplication.result=" + _getRolesApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignUserToApplication...");
        long _assignUserToApplication_idApp = -6138088055179434632l;
        long _assignUserToApplication_idUser = -8164026445368959686l;
        try {
            boolean _assignUserToApplication__return = port.assignUserToApplication(_assignUserToApplication_idApp, _assignUserToApplication_idUser);
            System.out.println("assignUserToApplication.result=" + _assignUserToApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (UserNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: UserNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getApplication...");
        long _getApplication_idApp = 7542884481834869903l;
        try {
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _getApplication__return = port.getApplication(_getApplication_idApp);
            System.out.println("getApplication.result=" + _getApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsApplication...");
        java.lang.String _existsApplication_nombreApp = "_existsApplication_nombreApp1808988567";
        boolean _existsApplication__return = port.existsApplication(_existsApplication_nombreApp);
        System.out.println("existsApplication.result=" + _existsApplication__return);


        }
        {
        System.out.println("Invoking existsEntityApplication...");
        long _existsEntityApplication_idApp = 5456538032156353984l;
        java.lang.String _existsEntityApplication_nomEntity = "_existsEntityApplication_nomEntity-1761790423";
        try {
            boolean _existsEntityApplication__return = port.existsEntityApplication(_existsEntityApplication_idApp, _existsEntityApplication_nomEntity);
            System.out.println("existsEntityApplication.result=" + _existsEntityApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsRoleApplication...");
        long _existsRoleApplication_idApp = 4360637777509740029l;
        java.lang.String _existsRoleApplication_nomRole = "_existsRoleApplication_nomRole445510706";
        try {
            boolean _existsRoleApplication__return = port.existsRoleApplication(_existsRoleApplication_idApp, _existsRoleApplication_nomRole);
            System.out.println("existsRoleApplication.result=" + _existsRoleApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannelApplication...");
        long _existsPushChannelApplication_idApp = 1258231158891378101l;
        java.lang.String _existsPushChannelApplication_nombreCanal = "_existsPushChannelApplication_nombreCanal196710568";
        try {
            boolean _existsPushChannelApplication__return = port.existsPushChannelApplication(_existsPushChannelApplication_idApp, _existsPushChannelApplication_nombreCanal);
            System.out.println("existsPushChannelApplication.result=" + _existsPushChannelApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignUserFromApplication...");
        long _unassignUserFromApplication_idApp = 4300115433122689595l;
        long _unassignUserFromApplication_idUser = -4452404717256576276l;
        try {
            boolean _unassignUserFromApplication__return = port.unassignUserFromApplication(_unassignUserFromApplication_idApp, _unassignUserFromApplication_idUser);
            System.out.println("unassignUserFromApplication.result=" + _unassignUserFromApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (UserNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: UserNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getChartsValues...");
        long _getChartsValues_idApp = 8020630534945056629l;
        try {
            uy.com.group05.baascore.sl.services.soap.ChartDto _getChartsValues__return = port.getChartsValues(_getChartsValues_idApp);
            System.out.println("getChartsValues.result=" + _getChartsValues__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking editEntityApplication...");
        long _editEntityApplication_idApp = 6697105171581715555l;
        long _editEntityApplication_idUser = 6995468006339039355l;
        java.lang.String _editEntityApplication_nomEntity = "_editEntityApplication_nomEntity130631408";
        try {
            long _editEntityApplication__return = port.editEntityApplication(_editEntityApplication_idApp, _editEntityApplication_idUser, _editEntityApplication_nomEntity);
            System.out.println("editEntityApplication.result=" + _editEntityApplication__return);

        } catch (EntityAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (EntityCollectionAlreadyExistsException_Exception e) { 
            System.out.println("Expected exception: EntityCollectionAlreadyExistsException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidNameException_Exception e) { 
            System.out.println("Expected exception: InvalidNameException has occurred.");
            System.out.println(e.toString());
        } catch (UserCantAccessAppException_Exception e) { 
            System.out.println("Expected exception: UserCantAccessAppException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
