
package uy.com.group05.baascore.sl.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-10-14T21:53:36.710-02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "EntityCollectionAlreadyExistsException", targetNamespace = "http://soap.services.sl.baascore.group05.com.uy/")
public class EntityCollectionAlreadyExistsException_Exception extends Exception {
    
    private uy.com.group05.baascore.sl.services.soap.EntityCollectionAlreadyExistsException entityCollectionAlreadyExistsException;

    public EntityCollectionAlreadyExistsException_Exception() {
        super();
    }
    
    public EntityCollectionAlreadyExistsException_Exception(String message) {
        super(message);
    }
    
    public EntityCollectionAlreadyExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EntityCollectionAlreadyExistsException_Exception(String message, uy.com.group05.baascore.sl.services.soap.EntityCollectionAlreadyExistsException entityCollectionAlreadyExistsException) {
        super(message);
        this.entityCollectionAlreadyExistsException = entityCollectionAlreadyExistsException;
    }

    public EntityCollectionAlreadyExistsException_Exception(String message, uy.com.group05.baascore.sl.services.soap.EntityCollectionAlreadyExistsException entityCollectionAlreadyExistsException, Throwable cause) {
        super(message, cause);
        this.entityCollectionAlreadyExistsException = entityCollectionAlreadyExistsException;
    }

    public uy.com.group05.baascore.sl.services.soap.EntityCollectionAlreadyExistsException getFaultInfo() {
        return this.entityCollectionAlreadyExistsException;
    }
}
