
package uy.com.group05.baascore.sl.services.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import uy.com.group05.baascore.sl.services.impl.PushServices;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-28T06:16:17.973-02:00
 * Generated source version: 2.4.6
 * 
 */
public final class PushChannelServices_PushServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.services.sl.baascore.group05.com.uy/", "PushServices");

    private PushChannelServices_PushServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PushServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PushServices ss = new PushServices(wsdlURL, SERVICE_NAME);
        PushChannelServices port = ss.getPushServicesPort();  
        
        {
        System.out.println("Invoking getPushChannelsOfApplication...");
        long _getPushChannelsOfApplication_arg0 = -4929663099508614881l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _getPushChannelsOfApplication__return = port.getPushChannelsOfApplication(_getPushChannelsOfApplication_arg0);
            System.out.println("getPushChannelsOfApplication.result=" + _getPushChannelsOfApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignEntityToPushChannel...");
        long _assignEntityToPushChannel_idApp = 7056012077193101349l;
        long _assignEntityToPushChannel_idCanal = -3953855369637754196l;
        long _assignEntityToPushChannel_idEntity = -5595997667260774449l;
        try {
            boolean _assignEntityToPushChannel__return = port.assignEntityToPushChannel(_assignEntityToPushChannel_idApp, _assignEntityToPushChannel_idCanal, _assignEntityToPushChannel_idEntity);
            System.out.println("assignEntityToPushChannel.result=" + _assignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendNotificationToPushChannel...");
        long _sendNotificationToPushChannel_idApp = 6735242832390948059l;
        long _sendNotificationToPushChannel_idCanal = -9019792655230381972l;
        java.lang.String _sendNotificationToPushChannel_msgKey = "_sendNotificationToPushChannel_msgKey744976725";
        java.lang.String _sendNotificationToPushChannel_msgValue = "_sendNotificationToPushChannel_msgValue2080191156";
        try {
            boolean _sendNotificationToPushChannel__return = port.sendNotificationToPushChannel(_sendNotificationToPushChannel_idApp, _sendNotificationToPushChannel_idCanal, _sendNotificationToPushChannel_msgKey, _sendNotificationToPushChannel_msgValue);
            System.out.println("sendNotificationToPushChannel.result=" + _sendNotificationToPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignClientToPushChannel...");
        long _assignClientToPushChannel_idCanal = 4393683366921992781l;
        long _assignClientToPushChannel_idCliente = -761930559806189770l;
        try {
            boolean _assignClientToPushChannel__return = port.assignClientToPushChannel(_assignClientToPushChannel_idCanal, _assignClientToPushChannel_idCliente);
            System.out.println("assignClientToPushChannel.result=" + _assignClientToPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignEntityToPushChannel...");
        long _unassignEntityToPushChannel_idApp = -969350015085348374l;
        long _unassignEntityToPushChannel_idCanal = -8686732385939062081l;
        long _unassignEntityToPushChannel_idEntity = 4799281474472742370l;
        try {
            boolean _unassignEntityToPushChannel__return = port.unassignEntityToPushChannel(_unassignEntityToPushChannel_idApp, _unassignEntityToPushChannel_idCanal, _unassignEntityToPushChannel_idEntity);
            System.out.println("unassignEntityToPushChannel.result=" + _unassignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking savePushChannelEntities...");
        long _savePushChannelEntities_idApp = -9023664653757828432l;
        long _savePushChannelEntities_idCanal = 2414229077248708928l;
        java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO> _savePushChannelEntities_entity = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO>();
        uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO _savePushChannelEntities_entityVal1 = new uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO();
        _savePushChannelEntities_entityVal1.setAssociated(true);
        _savePushChannelEntities_entityVal1.setId(4893485695084370630l);
        _savePushChannelEntities_entityVal1.setName("Name107343359");
        _savePushChannelEntities_entity.add(_savePushChannelEntities_entityVal1);
        try {
            boolean _savePushChannelEntities__return = port.savePushChannelEntities(_savePushChannelEntities_idApp, _savePushChannelEntities_idCanal, _savePushChannelEntities_entity);
            System.out.println("savePushChannelEntities.result=" + _savePushChannelEntities__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createPushChannel...");
        long _createPushChannel_idApp = 662041714659339248l;
        java.lang.String _createPushChannel_nombreCanal = "_createPushChannel_nombreCanal310853534";
        try {
            long _createPushChannel__return = port.createPushChannel(_createPushChannel_idApp, _createPushChannel_nombreCanal);
            System.out.println("createPushChannel.result=" + _createPushChannel__return);

        } catch (PushChanAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignClientFromPushChannel...");
        long _unassignClientFromPushChannel_idApp = 7054242095820483786l;
        long _unassignClientFromPushChannel_idCanal = 2648694167203467373l;
        long _unassignClientFromPushChannel_idCliente = -6692112543072047951l;
        try {
            boolean _unassignClientFromPushChannel__return = port.unassignClientFromPushChannel(_unassignClientFromPushChannel_idApp, _unassignClientFromPushChannel_idCanal, _unassignClientFromPushChannel_idCliente);
            System.out.println("unassignClientFromPushChannel.result=" + _unassignClientFromPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientsFromPushChannel...");
        long _getClientsFromPushChannel_idApp = 7244491081632867789l;
        long _getClientsFromPushChannel_idCanal = -1032630256191918353l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _getClientsFromPushChannel__return = port.getClientsFromPushChannel(_getClientsFromPushChannel_idApp, _getClientsFromPushChannel_idCanal);
            System.out.println("getClientsFromPushChannel.result=" + _getClientsFromPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannelApplication...");
        long _existsPushChannelApplication_idApp = -764333707059427662l;
        java.lang.String _existsPushChannelApplication_nombreCanal = "_existsPushChannelApplication_nombreCanal-1529711830";
        try {
            boolean _existsPushChannelApplication__return = port.existsPushChannelApplication(_existsPushChannelApplication_idApp, _existsPushChannelApplication_nombreCanal);
            System.out.println("existsPushChannelApplication.result=" + _existsPushChannelApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEntitiesAssociatedWithPushChannel...");
        long _getEntitiesAssociatedWithPushChannel_idApp = -2210116886361018352l;
        long _getEntitiesAssociatedWithPushChannel_idCanal = 3342846017134315262l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO> _getEntitiesAssociatedWithPushChannel__return = port.getEntitiesAssociatedWithPushChannel(_getEntitiesAssociatedWithPushChannel_idApp, _getEntitiesAssociatedWithPushChannel_idCanal);
            System.out.println("getEntitiesAssociatedWithPushChannel.result=" + _getEntitiesAssociatedWithPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deletePushChannel...");
        long _deletePushChannel_idApp = -6076178826842925519l;
        long _deletePushChannel_idCanal = 2936973479381403183l;
        try {
            long _deletePushChannel__return = port.deletePushChannel(_deletePushChannel_idApp, _deletePushChannel_idCanal);
            System.out.println("deletePushChannel.result=" + _deletePushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannel...");
        long _existsPushChannel_idCanal = 8353374769730024304l;
        boolean _existsPushChannel__return = port.existsPushChannel(_existsPushChannel_idCanal);
        System.out.println("existsPushChannel.result=" + _existsPushChannel__return);


        }

        System.exit(0);
    }

}
