
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uy.com.group05.baascore.sl.services.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-10-27T17:42:53.507-02:00
 * Generated source version: 2.4.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "PushServices",
                      portName = "PushServicesPort",
                      targetNamespace = "http://impl.services.sl.baascore.group05.com.uy/",
                      wsdlLocation = "http://localhost:8080/baas-core/PushServices?wsdl",
                      endpointInterface = "uy.com.group05.baascore.sl.services.soap.PushChannelServices")
                      
public class PushChannelServicesImpl implements PushChannelServices {

    private static final Logger LOG = Logger.getLogger(PushChannelServicesImpl.class.getName());

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#getPushChannelsOfApplication(long  arg0 )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> getPushChannelsOfApplication(long arg0) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPushChannelsOfApplication");
        System.out.println(arg0);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO>();
            uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-1840099433");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-737627890922037536l);
            _returnVal1Application.setName("Name-649174992");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1Clients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1ClientsVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1ClientsVal1.setAppName("AppName-518079445");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1ClientsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1ClientsVal1Application.setApiClientId("ApiClientId1117691832");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ClientsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1ClientsVal1Application.getClients().addAll(_returnVal1ClientsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ClientsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1ClientsVal1Application.getEntities().addAll(_returnVal1ClientsVal1ApplicationEntities);
            _returnVal1ClientsVal1Application.setId(5507828076685878127l);
            _returnVal1ClientsVal1Application.setName("Name1439854715");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ClientsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1ClientsVal1Application.getRoles().addAll(_returnVal1ClientsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ClientsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1ClientsVal1Application.getUsers().addAll(_returnVal1ClientsVal1ApplicationUsers);
            _returnVal1ClientsVal1.setApplication(_returnVal1ClientsVal1Application);
            _returnVal1ClientsVal1.setEmail("Email260698871");
            _returnVal1ClientsVal1.setId(6393058784528906576l);
            _returnVal1ClientsVal1.setLastname("Lastname-1416366665");
            _returnVal1ClientsVal1.setName("Name-1765261587");
            _returnVal1ClientsVal1.setPassword("Password-1785827598");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1ClientsVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            _returnVal1ClientsVal1.getRoles().addAll(_returnVal1ClientsVal1Roles);
            _returnVal1Clients.add(_returnVal1ClientsVal1);
            _returnVal1.getClients().addAll(_returnVal1Clients);
            _returnVal1.setId(7695706653976261997l);
            _returnVal1.setName("Name716133136");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#assignEntityToPushChannel(long  idApp ,)long  idCanal ,)long  idEntity )*
     */
    public boolean assignEntityToPushChannel(long idApp,long idCanal,long idEntity) throws EntityNotRegisteredException_Exception , PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation assignEntityToPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(idEntity);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityNotRegisteredException_Exception("EntityNotRegisteredException...");
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#sendNotificationToPushChannel(long  idApp ,)long  idCanal ,)java.lang.String  mensaje )*
     */
    public boolean sendNotificationToPushChannel(long idApp,long idCanal,java.lang.String mensaje) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation sendNotificationToPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(mensaje);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#assignClientToPushChannel(long  idApp ,)long  idCanal ,)long  idCliente )*
     */
    public boolean assignClientToPushChannel(long idApp,long idCanal,long idCliente) throws ClientNotRegisteredException_Exception , PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation assignClientToPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(idCliente);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClientNotRegisteredException_Exception("ClientNotRegisteredException...");
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#unassignEntityToPushChannel(long  idApp ,)long  idCanal ,)long  idEntity )*
     */
    public boolean unassignEntityToPushChannel(long idApp,long idCanal,long idEntity) throws EntityNotRegisteredException_Exception , PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation unassignEntityToPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(idEntity);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityNotRegisteredException_Exception("EntityNotRegisteredException...");
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#savePushChannelEntities(long  idApp ,)long  idCanal ,)java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO>  entity )*
     */
    public boolean savePushChannelEntities(long idApp,long idCanal,java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO> entity) throws EntityNotRegisteredException_Exception , PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation savePushChannelEntities");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(entity);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityNotRegisteredException_Exception("EntityNotRegisteredException...");
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#createPushChannel(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public long createPushChannel(long idApp,java.lang.String nombreCanal) throws PushChanAlreadyRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation createPushChannel");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            long _return = 8905390974964924530l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanAlreadyRegisteredException_Exception("PushChanAlreadyRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#unassignClientFromPushChannel(long  idApp ,)long  idCanal ,)long  idCliente )*
     */
    public boolean unassignClientFromPushChannel(long idApp,long idCanal,long idCliente) throws ClientNotRegisteredException_Exception , PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation unassignClientFromPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        System.out.println(idCliente);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClientNotRegisteredException_Exception("ClientNotRegisteredException...");
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#getClientsFromPushChannel(long  idApp ,)long  idCanal )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> getClientsFromPushChannel(long idApp,long idCanal) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getClientsFromPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1.setAppName("AppName-2124649342");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-857668936");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-4700121146808654370l);
            _returnVal1Application.setName("Name-1532709027");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setEmail("Email539180370");
            _returnVal1.setId(-3415940797296144057l);
            _returnVal1.setLastname("Lastname-2113304421");
            _returnVal1.setName("Name-1767709559");
            _returnVal1.setPassword("Password96835870");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO _returnVal1RolesVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO();
            _returnVal1RolesVal1.setId(8066751117377448018l);
            _returnVal1RolesVal1.setName("Name-1184690667");
            _returnVal1Roles.add(_returnVal1RolesVal1);
            _returnVal1.getRoles().addAll(_returnVal1Roles);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#existsPushChannelApplication(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public boolean existsPushChannelApplication(long idApp,java.lang.String nombreCanal) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsPushChannelApplication");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#getEntitiesAssociatedWithPushChannel(long  idApp ,)long  idCanal )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO> getEntitiesAssociatedWithPushChannel(long idApp,long idCanal) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getEntitiesAssociatedWithPushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO();
            _returnVal1.setId(205519215325844758l);
            _returnVal1.setName("Name2011020746");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#deletePushChannel(long  idApp ,)long  idCanal )*
     */
    public long deletePushChannel(long idApp,long idCanal) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation deletePushChannel");
        System.out.println(idApp);
        System.out.println(idCanal);
        try {
            long _return = -2371652837446693107l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.PushChannelServices#existsPushChannel(long  idCanal )*
     */
    public boolean existsPushChannel(long idCanal) { 
        LOG.info("Executing operation existsPushChannel");
        System.out.println(idCanal);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
