
package uy.com.group05.baascore.sl.services.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import uy.com.group05.baascore.sl.services.impl.PushServices;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-09T15:52:49.251-02:00
 * Generated source version: 2.4.6
 * 
 */
public final class PushChannelServices_PushServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.services.sl.baascore.group05.com.uy/", "PushServices");

    private PushChannelServices_PushServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PushServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PushServices ss = new PushServices(wsdlURL, SERVICE_NAME);
        PushChannelServices port = ss.getPushServicesPort();  
        
        {
        System.out.println("Invoking getPushChannelsOfApplication...");
        long _getPushChannelsOfApplication_arg0 = -4377203993380723511l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _getPushChannelsOfApplication__return = port.getPushChannelsOfApplication(_getPushChannelsOfApplication_arg0);
            System.out.println("getPushChannelsOfApplication.result=" + _getPushChannelsOfApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignEntityToPushChannel...");
        long _assignEntityToPushChannel_idApp = -2813028199823521626l;
        long _assignEntityToPushChannel_idCanal = -3993507600950836503l;
        long _assignEntityToPushChannel_idEntity = 7709276172324619252l;
        try {
            boolean _assignEntityToPushChannel__return = port.assignEntityToPushChannel(_assignEntityToPushChannel_idApp, _assignEntityToPushChannel_idCanal, _assignEntityToPushChannel_idEntity);
            System.out.println("assignEntityToPushChannel.result=" + _assignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendNotificationToPushChannel...");
        long _sendNotificationToPushChannel_idApp = 826930400469917097l;
        long _sendNotificationToPushChannel_idCanal = 138774258365674599l;
        java.lang.String _sendNotificationToPushChannel_msgKey = "_sendNotificationToPushChannel_msgKey380426812";
        java.lang.String _sendNotificationToPushChannel_msgValue = "_sendNotificationToPushChannel_msgValue-685976149";
        try {
            boolean _sendNotificationToPushChannel__return = port.sendNotificationToPushChannel(_sendNotificationToPushChannel_idApp, _sendNotificationToPushChannel_idCanal, _sendNotificationToPushChannel_msgKey, _sendNotificationToPushChannel_msgValue);
            System.out.println("sendNotificationToPushChannel.result=" + _sendNotificationToPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignClientToPushChannel...");
        long _assignClientToPushChannel_idCanal = -8922072173957440763l;
        long _assignClientToPushChannel_idCliente = -7529732081797036991l;
        try {
            boolean _assignClientToPushChannel__return = port.assignClientToPushChannel(_assignClientToPushChannel_idCanal, _assignClientToPushChannel_idCliente);
            System.out.println("assignClientToPushChannel.result=" + _assignClientToPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignEntityToPushChannel...");
        long _unassignEntityToPushChannel_idApp = 3946771967456145912l;
        long _unassignEntityToPushChannel_idCanal = -7766575291387842073l;
        long _unassignEntityToPushChannel_idEntity = -6120503991805742923l;
        try {
            boolean _unassignEntityToPushChannel__return = port.unassignEntityToPushChannel(_unassignEntityToPushChannel_idApp, _unassignEntityToPushChannel_idCanal, _unassignEntityToPushChannel_idEntity);
            System.out.println("unassignEntityToPushChannel.result=" + _unassignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking savePushChannelEntities...");
        long _savePushChannelEntities_idApp = 2289542219107168532l;
        long _savePushChannelEntities_idCanal = -8114983428931129760l;
        java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO> _savePushChannelEntities_entity = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO>();
        uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO _savePushChannelEntities_entityVal1 = new uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO();
        _savePushChannelEntities_entityVal1.setAssociated(true);
        _savePushChannelEntities_entityVal1.setId(5040127426705648470l);
        _savePushChannelEntities_entityVal1.setName("Name-803862929");
        _savePushChannelEntities_entity.add(_savePushChannelEntities_entityVal1);
        try {
            boolean _savePushChannelEntities__return = port.savePushChannelEntities(_savePushChannelEntities_idApp, _savePushChannelEntities_idCanal, _savePushChannelEntities_entity);
            System.out.println("savePushChannelEntities.result=" + _savePushChannelEntities__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createPushChannel...");
        long _createPushChannel_idApp = 6841462186435894761l;
        java.lang.String _createPushChannel_nombreCanal = "_createPushChannel_nombreCanal-934550759";
        try {
            long _createPushChannel__return = port.createPushChannel(_createPushChannel_idApp, _createPushChannel_nombreCanal);
            System.out.println("createPushChannel.result=" + _createPushChannel__return);

        } catch (PushChanAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignClientFromPushChannel...");
        long _unassignClientFromPushChannel_idApp = 5956964388728326033l;
        long _unassignClientFromPushChannel_idCanal = -3212510594359894287l;
        long _unassignClientFromPushChannel_idCliente = -1959676342326260966l;
        try {
            boolean _unassignClientFromPushChannel__return = port.unassignClientFromPushChannel(_unassignClientFromPushChannel_idApp, _unassignClientFromPushChannel_idCanal, _unassignClientFromPushChannel_idCliente);
            System.out.println("unassignClientFromPushChannel.result=" + _unassignClientFromPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientsFromPushChannel...");
        long _getClientsFromPushChannel_idApp = -4435682467502171705l;
        long _getClientsFromPushChannel_idCanal = 5374079463373635501l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _getClientsFromPushChannel__return = port.getClientsFromPushChannel(_getClientsFromPushChannel_idApp, _getClientsFromPushChannel_idCanal);
            System.out.println("getClientsFromPushChannel.result=" + _getClientsFromPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannelApplication...");
        long _existsPushChannelApplication_idApp = -6234878159008509692l;
        java.lang.String _existsPushChannelApplication_nombreCanal = "_existsPushChannelApplication_nombreCanal-1491448870";
        try {
            boolean _existsPushChannelApplication__return = port.existsPushChannelApplication(_existsPushChannelApplication_idApp, _existsPushChannelApplication_nombreCanal);
            System.out.println("existsPushChannelApplication.result=" + _existsPushChannelApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEntitiesAssociatedWithPushChannel...");
        long _getEntitiesAssociatedWithPushChannel_idApp = -9189382738555326452l;
        long _getEntitiesAssociatedWithPushChannel_idCanal = 680924848219718485l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO> _getEntitiesAssociatedWithPushChannel__return = port.getEntitiesAssociatedWithPushChannel(_getEntitiesAssociatedWithPushChannel_idApp, _getEntitiesAssociatedWithPushChannel_idCanal);
            System.out.println("getEntitiesAssociatedWithPushChannel.result=" + _getEntitiesAssociatedWithPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deletePushChannel...");
        long _deletePushChannel_idApp = -9043444057062391051l;
        long _deletePushChannel_idCanal = -3131479580520799211l;
        try {
            long _deletePushChannel__return = port.deletePushChannel(_deletePushChannel_idApp, _deletePushChannel_idCanal);
            System.out.println("deletePushChannel.result=" + _deletePushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannel...");
        long _existsPushChannel_idCanal = -7982558883817289797l;
        boolean _existsPushChannel__return = port.existsPushChannel(_existsPushChannel_idCanal);
        System.out.println("existsPushChannel.result=" + _existsPushChannel__return);


        }

        System.exit(0);
    }

}
