
package uy.com.group05.baascore.sl.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-09T15:52:37.558-02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "RoleNotRegisteredException", targetNamespace = "http://soap.services.sl.baascore.group05.com.uy/")
public class RoleNotRegisteredException_Exception extends Exception {
    
    private uy.com.group05.baascore.sl.services.soap.RoleNotRegisteredException roleNotRegisteredException;

    public RoleNotRegisteredException_Exception() {
        super();
    }
    
    public RoleNotRegisteredException_Exception(String message) {
        super(message);
    }
    
    public RoleNotRegisteredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RoleNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.RoleNotRegisteredException roleNotRegisteredException) {
        super(message);
        this.roleNotRegisteredException = roleNotRegisteredException;
    }

    public RoleNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.RoleNotRegisteredException roleNotRegisteredException, Throwable cause) {
        super(message, cause);
        this.roleNotRegisteredException = roleNotRegisteredException;
    }

    public uy.com.group05.baascore.sl.services.soap.RoleNotRegisteredException getFaultInfo() {
        return this.roleNotRegisteredException;
    }
}
