
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uy.com.group05.baascore.sl.services.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-28T00:17:48.856-02:00
 * Generated source version: 2.4.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ApplicationServices",
                      portName = "ApplicationServicesPort",
                      targetNamespace = "http://impl.services.sl.baascore.group05.com.uy/",
                      wsdlLocation = "http://localhost:8080/baas-core/ApplicationServices?wsdl",
                      endpointInterface = "uy.com.group05.baascore.sl.services.soap.ApplicationServices")
                      
public class ApplicationServicesImpl implements ApplicationServices {

    private static final Logger LOG = Logger.getLogger(ApplicationServicesImpl.class.getName());

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#addPushChannelToApplication(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public long addPushChannelToApplication(long idApp,java.lang.String nombreCanal) throws PushChanAlreadyRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation addPushChannelToApplication");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            long _return = 9192868066037199675l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanAlreadyRegisteredException_Exception("PushChanAlreadyRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#createApplication(long  idUser ,)java.lang.String  nombreApp ,)java.util.List<java.lang.String>  rolStr ,)java.util.List<java.lang.String>  entidadStr ,)java.util.List<java.lang.Boolean>  entidadSync )*
     */
    public long createApplication(long idUser,java.lang.String nombreApp,java.util.List<java.lang.String> rolStr,java.util.List<java.lang.String> entidadStr,java.util.List<java.lang.Boolean> entidadSync) throws NombreAppAlreadyRegisteredException_Exception , MongoDBAlreadyExistsException_Exception , EntityCollectionAlreadyExistsException_Exception , InvalidNameException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation createApplication");
        System.out.println(idUser);
        System.out.println(nombreApp);
        System.out.println(rolStr);
        System.out.println(entidadStr);
        System.out.println(entidadSync);
        try {
            long _return = -3150707355051149569l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NombreAppAlreadyRegisteredException_Exception("NombreAppAlreadyRegisteredException...");
        //throw new MongoDBAlreadyExistsException_Exception("MongoDBAlreadyExistsException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editApplication(java.lang.String  nombreApp ,)java.util.List<java.lang.String>  rolStr ,)java.util.List<java.lang.String>  entidadStr )*
     */
    public long editApplication(java.lang.String nombreApp,java.util.List<java.lang.String> rolStr,java.util.List<java.lang.String> entidadStr) throws MongoDBAlreadyExistsException_Exception , EntityCollectionAlreadyExistsException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editApplication");
        System.out.println(nombreApp);
        System.out.println(rolStr);
        System.out.println(entidadStr);
        try {
            long _return = -2949903879659090883l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new MongoDBAlreadyExistsException_Exception("MongoDBAlreadyExistsException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#removePushChannelFromApplication(long  idApp ,)long  idCanal )*
     */
    public long removePushChannelFromApplication(long idApp,long idCanal) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation removePushChannelFromApplication");
        System.out.println(idApp);
        System.out.println(idCanal);
        try {
            long _return = 8740796532077654953l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getRoleName(long  arg0 ,)long  arg1 )*
     */
    public java.lang.String getRoleName(long arg0,long arg1) throws RoleNotFoundException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getRoleName");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-152148567";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RoleNotFoundException_Exception("RoleNotFoundException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#listApplications(long  idUser )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO> listApplications(long idUser) throws UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation listApplications");
        System.out.println(idUser);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO();
            _returnVal1.setApiClientId("ApiClientId-926228778");
            _returnVal1.setId(-4607776239459932322l);
            _returnVal1.setName("Name1287057999");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getPermissionsForEntity(long  appId ,)long  entityId )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> getPermissionsForEntity(long appId,long entityId) throws EntityCollectionNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPermissionsForEntity");
        System.out.println(appId);
        System.out.println(entityId);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            uy.com.group05.baascore.sl.services.soap.PermissionDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.PermissionDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-1304676683");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-4785781326885062087l);
            _returnVal1Application.setName("Name-108098296");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1Entity = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1EntityApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1EntityApplication.setApiClientId("ApiClientId305774161");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1EntityApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1EntityApplication.getClients().addAll(_returnVal1EntityApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1EntityApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1EntityApplication.getEntities().addAll(_returnVal1EntityApplicationEntities);
            _returnVal1EntityApplication.setId(-7463524564127957877l);
            _returnVal1EntityApplication.setName("Name295556800");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1EntityApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1EntityApplication.getRoles().addAll(_returnVal1EntityApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1EntityApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1EntityApplication.getUsers().addAll(_returnVal1EntityApplicationUsers);
            _returnVal1Entity.setApplication(_returnVal1EntityApplication);
            _returnVal1Entity.setId(5281697737929574762l);
            _returnVal1Entity.setName("Name475539763");
            _returnVal1Entity.setSync(true);
            _returnVal1.setEntity(_returnVal1Entity);
            _returnVal1.setId(-298171095492703787l);
            uy.com.group05.baascore.sl.services.soap.OperationDTO _returnVal1Operation = new uy.com.group05.baascore.sl.services.soap.OperationDTO();
            _returnVal1Operation.setId(5643776912425755919l);
            _returnVal1Operation.setName("Name2139020778");
            _returnVal1.setOperation(_returnVal1Operation);
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1Role = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1RoleApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1RoleApplication.setApiClientId("ApiClientId-1144814610");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1RoleApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1RoleApplication.getClients().addAll(_returnVal1RoleApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1RoleApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1RoleApplication.getEntities().addAll(_returnVal1RoleApplicationEntities);
            _returnVal1RoleApplication.setId(-5166301128963073024l);
            _returnVal1RoleApplication.setName("Name-1644220659");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1RoleApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1RoleApplication.getRoles().addAll(_returnVal1RoleApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1RoleApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1RoleApplication.getUsers().addAll(_returnVal1RoleApplicationUsers);
            _returnVal1Role.setApplication(_returnVal1RoleApplication);
            _returnVal1Role.setId(8163441532944919574l);
            _returnVal1Role.setName("Name815651692");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1RolePermissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnVal1Role.getPermissions().addAll(_returnVal1RolePermissions);
            _returnVal1.setRole(_returnVal1Role);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityCollectionNotRegisteredException_Exception("EntityCollectionNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getPushChannelsApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> getPushChannelsApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPushChannelsApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO>();
            uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-1825793592");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(798502921796413782l);
            _returnVal1Application.setName("Name-1269359846");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1Clients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1ClientsVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1ClientsVal1.setAppName("AppName1618856003");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1ClientsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1ClientsVal1Application.setApiClientId("ApiClientId1033036949");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ClientsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1ClientsVal1Application.getClients().addAll(_returnVal1ClientsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ClientsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1ClientsVal1Application.getEntities().addAll(_returnVal1ClientsVal1ApplicationEntities);
            _returnVal1ClientsVal1Application.setId(7090951200693084428l);
            _returnVal1ClientsVal1Application.setName("Name-1031783402");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ClientsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1ClientsVal1Application.getRoles().addAll(_returnVal1ClientsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ClientsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1ClientsVal1Application.getUsers().addAll(_returnVal1ClientsVal1ApplicationUsers);
            _returnVal1ClientsVal1.setApplication(_returnVal1ClientsVal1Application);
            _returnVal1ClientsVal1.setEmail("Email-1153518541");
            _returnVal1ClientsVal1.setId(217286354048287932l);
            _returnVal1ClientsVal1.setLastname("Lastname-1228371389");
            _returnVal1ClientsVal1.setName("Name-290224728");
            _returnVal1ClientsVal1.setPassword("Password-78933251");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1ClientsVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            _returnVal1ClientsVal1.getRoles().addAll(_returnVal1ClientsVal1Roles);
            _returnVal1Clients.add(_returnVal1ClientsVal1);
            _returnVal1.getClients().addAll(_returnVal1Clients);
            _returnVal1.setId(-6730732274551758234l);
            _returnVal1.setName("Name-1841896147");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editRoleApplication(long  idApp ,)long  idUser ,)java.lang.String  nomRole )*
     */
    public long editRoleApplication(long idApp,long idUser,java.lang.String nomRole) throws RoleAlreadyRegisteredException_Exception , InvalidNameException_Exception , UserCantAccessAppException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editRoleApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        System.out.println(nomRole);
        try {
            long _return = 8910682191975056400l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RoleAlreadyRegisteredException_Exception("RoleAlreadyRegisteredException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserCantAccessAppException_Exception("UserCantAccessAppException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getEntitiesApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> getEntitiesApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getEntitiesApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId449467690");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(12074818171540328l);
            _returnVal1Application.setName("Name2071379710");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setId(287260602305473518l);
            _returnVal1.setName("Name-471260694");
            _returnVal1.setSync(false);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getClientsApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> getClientsApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getClientsApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1.setAppName("AppName1350497289");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-625808539");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-8143335108199070897l);
            _returnVal1Application.setName("Name8611419");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setEmail("Email1001866091");
            _returnVal1.setId(-629932924996420527l);
            _returnVal1.setLastname("Lastname-1421736092");
            _returnVal1.setName("Name1804178971");
            _returnVal1.setPassword("Password-808317693");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO _returnVal1RolesVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO();
            _returnVal1RolesVal1.setId(4948039677190654889l);
            _returnVal1RolesVal1.setName("Name-1108393153");
            _returnVal1Roles.add(_returnVal1RolesVal1);
            _returnVal1.getRoles().addAll(_returnVal1Roles);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getRolesApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> getRolesApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getRolesApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId867897322");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-1699980317854482508l);
            _returnVal1Application.setName("Name-1379112646");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setId(-4368453625634997127l);
            _returnVal1.setName("Name-1579075253");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1Permissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            uy.com.group05.baascore.sl.services.soap.PermissionDTO _returnVal1PermissionsVal1 = new uy.com.group05.baascore.sl.services.soap.PermissionDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1Application.setApiClientId("ApiClientId291278888");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1Application.getClients().addAll(_returnVal1PermissionsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1Application.getEntities().addAll(_returnVal1PermissionsVal1ApplicationEntities);
            _returnVal1PermissionsVal1Application.setId(-4067681402914489467l);
            _returnVal1PermissionsVal1Application.setName("Name397961189");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1Application.getRoles().addAll(_returnVal1PermissionsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1Application.getUsers().addAll(_returnVal1PermissionsVal1ApplicationUsers);
            _returnVal1PermissionsVal1.setApplication(_returnVal1PermissionsVal1Application);
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1PermissionsVal1Entity = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1EntityApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1EntityApplication.setApiClientId("ApiClientId-1079483581");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1EntityApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1EntityApplication.getClients().addAll(_returnVal1PermissionsVal1EntityApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1EntityApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1EntityApplication.getEntities().addAll(_returnVal1PermissionsVal1EntityApplicationEntities);
            _returnVal1PermissionsVal1EntityApplication.setId(672243444341208296l);
            _returnVal1PermissionsVal1EntityApplication.setName("Name-1627654055");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1EntityApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1EntityApplication.getRoles().addAll(_returnVal1PermissionsVal1EntityApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1EntityApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1EntityApplication.getUsers().addAll(_returnVal1PermissionsVal1EntityApplicationUsers);
            _returnVal1PermissionsVal1Entity.setApplication(_returnVal1PermissionsVal1EntityApplication);
            _returnVal1PermissionsVal1Entity.setId(-7614711173229918185l);
            _returnVal1PermissionsVal1Entity.setName("Name-390983767");
            _returnVal1PermissionsVal1Entity.setSync(false);
            _returnVal1PermissionsVal1.setEntity(_returnVal1PermissionsVal1Entity);
            _returnVal1PermissionsVal1.setId(-3215422142717232069l);
            uy.com.group05.baascore.sl.services.soap.OperationDTO _returnVal1PermissionsVal1Operation = new uy.com.group05.baascore.sl.services.soap.OperationDTO();
            _returnVal1PermissionsVal1Operation.setId(-7411511570099101155l);
            _returnVal1PermissionsVal1Operation.setName("Name-717309723");
            _returnVal1PermissionsVal1.setOperation(_returnVal1PermissionsVal1Operation);
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1PermissionsVal1Role = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1RoleApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1RoleApplication.setApiClientId("ApiClientId-519627241");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1RoleApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1RoleApplication.getClients().addAll(_returnVal1PermissionsVal1RoleApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1RoleApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1RoleApplication.getEntities().addAll(_returnVal1PermissionsVal1RoleApplicationEntities);
            _returnVal1PermissionsVal1RoleApplication.setId(-706161796310292766l);
            _returnVal1PermissionsVal1RoleApplication.setName("Name-1972571643");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1RoleApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1RoleApplication.getRoles().addAll(_returnVal1PermissionsVal1RoleApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1RoleApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1RoleApplication.getUsers().addAll(_returnVal1PermissionsVal1RoleApplicationUsers);
            _returnVal1PermissionsVal1Role.setApplication(_returnVal1PermissionsVal1RoleApplication);
            _returnVal1PermissionsVal1Role.setId(-8310370931451830382l);
            _returnVal1PermissionsVal1Role.setName("Name-394235243");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1PermissionsVal1RolePermissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnVal1PermissionsVal1Role.getPermissions().addAll(_returnVal1PermissionsVal1RolePermissions);
            _returnVal1PermissionsVal1.setRole(_returnVal1PermissionsVal1Role);
            _returnVal1Permissions.add(_returnVal1PermissionsVal1);
            _returnVal1.getPermissions().addAll(_returnVal1Permissions);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#assignUserToApplication(long  idApp ,)long  idUser )*
     */
    public boolean assignUserToApplication(long idApp,long idUser) throws AppNotRegisteredException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation assignUserToApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getApplication(long  idApp )*
     */
    public uy.com.group05.baascore.sl.services.soap.ApplicationDTO getApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getApplication");
        System.out.println(idApp);
        try {
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _return = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _return.setApiClientId("ApiClientId103956735");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnClientsVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnClientsVal1.setAppName("AppName3197652");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnClientsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnClientsVal1Application.setApiClientId("ApiClientId1488688715");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnClientsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnClientsVal1Application.getClients().addAll(_returnClientsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnClientsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnClientsVal1Application.getEntities().addAll(_returnClientsVal1ApplicationEntities);
            _returnClientsVal1Application.setId(1095651462683447092l);
            _returnClientsVal1Application.setName("Name-260137477");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnClientsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnClientsVal1Application.getRoles().addAll(_returnClientsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnClientsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnClientsVal1Application.getUsers().addAll(_returnClientsVal1ApplicationUsers);
            _returnClientsVal1.setApplication(_returnClientsVal1Application);
            _returnClientsVal1.setEmail("Email54684405");
            _returnClientsVal1.setId(-162114872511780651l);
            _returnClientsVal1.setLastname("Lastname708356781");
            _returnClientsVal1.setName("Name1243638737");
            _returnClientsVal1.setPassword("Password-1876742861");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnClientsVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            _returnClientsVal1.getRoles().addAll(_returnClientsVal1Roles);
            _returnClients.add(_returnClientsVal1);
            _return.getClients().addAll(_returnClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnEntitiesVal1 = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnEntitiesVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnEntitiesVal1Application.setApiClientId("ApiClientId-640756366");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnEntitiesVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnEntitiesVal1Application.getClients().addAll(_returnEntitiesVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnEntitiesVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnEntitiesVal1Application.getEntities().addAll(_returnEntitiesVal1ApplicationEntities);
            _returnEntitiesVal1Application.setId(5978583026130043938l);
            _returnEntitiesVal1Application.setName("Name376549827");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnEntitiesVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnEntitiesVal1Application.getRoles().addAll(_returnEntitiesVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnEntitiesVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnEntitiesVal1Application.getUsers().addAll(_returnEntitiesVal1ApplicationUsers);
            _returnEntitiesVal1.setApplication(_returnEntitiesVal1Application);
            _returnEntitiesVal1.setId(4071868069511914160l);
            _returnEntitiesVal1.setName("Name421266466");
            _returnEntitiesVal1.setSync(true);
            _returnEntities.add(_returnEntitiesVal1);
            _return.getEntities().addAll(_returnEntities);
            _return.setId(-5546711698183512635l);
            _return.setName("Name-552586953");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnRolesVal1 = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnRolesVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnRolesVal1Application.setApiClientId("ApiClientId-504737886");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnRolesVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnRolesVal1Application.getClients().addAll(_returnRolesVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnRolesVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnRolesVal1Application.getEntities().addAll(_returnRolesVal1ApplicationEntities);
            _returnRolesVal1Application.setId(6357343216065754929l);
            _returnRolesVal1Application.setName("Name-156818075");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnRolesVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnRolesVal1Application.getRoles().addAll(_returnRolesVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnRolesVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnRolesVal1Application.getUsers().addAll(_returnRolesVal1ApplicationUsers);
            _returnRolesVal1.setApplication(_returnRolesVal1Application);
            _returnRolesVal1.setId(476068587632254829l);
            _returnRolesVal1.setName("Name1233798380");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnRolesVal1Permissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnRolesVal1.getPermissions().addAll(_returnRolesVal1Permissions);
            _returnRoles.add(_returnRolesVal1);
            _return.getRoles().addAll(_returnRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            uy.com.group05.baascore.sl.services.soap.UserDTO _returnUsersVal1 = new uy.com.group05.baascore.sl.services.soap.UserDTO();
            _returnUsersVal1.setEmail("Email-785419772");
            _returnUsersVal1.setId(7434376148942049651l);
            _returnUsersVal1.setLastname("Lastname-846972985");
            _returnUsersVal1.setLoggedIn(false);
            _returnUsersVal1.setName("Name-1546294246");
            _returnUsers.add(_returnUsersVal1);
            _return.getUsers().addAll(_returnUsers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsEntityApplication(long  idApp ,)java.lang.String  nomEntity )*
     */
    public boolean existsEntityApplication(long idApp,java.lang.String nomEntity) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsEntityApplication");
        System.out.println(idApp);
        System.out.println(nomEntity);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getEntityName(long  arg0 ,)long  arg1 )*
     */
    public java.lang.String getEntityName(long arg0,long arg1) throws EntityCollectionNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getEntityName");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return1599489270";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityCollectionNotRegisteredException_Exception("EntityCollectionNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getChartsValues(long  idApp ,)uy.com.group05.baascore.sl.services.soap.TipoChart  tipoChart )*
     */
    public uy.com.group05.baascore.sl.services.soap.ChartDto getChartsValues(long idApp,uy.com.group05.baascore.sl.services.soap.TipoChart tipoChart) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getChartsValues");
        System.out.println(idApp);
        System.out.println(tipoChart);
        try {
            uy.com.group05.baascore.sl.services.soap.ChartDto _return = new uy.com.group05.baascore.sl.services.soap.ChartDto();
            java.util.List<java.lang.Integer> _returnDispRegistrados = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnDispRegistradosVal1 = Integer.valueOf(1319482762);
            _returnDispRegistrados.add(_returnDispRegistradosVal1);
            _return.getDispRegistrados().addAll(_returnDispRegistrados);
            java.util.List<java.lang.Integer> _returnMensajesPushEnviados = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnMensajesPushEnviadosVal1 = Integer.valueOf(-147864604);
            _returnMensajesPushEnviados.add(_returnMensajesPushEnviadosVal1);
            _return.getMensajesPushEnviados().addAll(_returnMensajesPushEnviados);
            java.util.List<java.lang.Integer> _returnPedidosHttp = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnPedidosHttpVal1 = Integer.valueOf(892866353);
            _returnPedidosHttp.add(_returnPedidosHttpVal1);
            _return.getPedidosHttp().addAll(_returnPedidosHttp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getPermissionsForRol(long  appId ,)long  rolId )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> getPermissionsForRol(long appId,long rolId) throws RoleNotFoundException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPermissionsForRol");
        System.out.println(appId);
        System.out.println(rolId);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            uy.com.group05.baascore.sl.services.soap.PermissionDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.PermissionDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId754312142");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-6619348530485259437l);
            _returnVal1Application.setName("Name428065559");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1Entity = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1EntityApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1EntityApplication.setApiClientId("ApiClientId520020942");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1EntityApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1EntityApplication.getClients().addAll(_returnVal1EntityApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1EntityApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1EntityApplication.getEntities().addAll(_returnVal1EntityApplicationEntities);
            _returnVal1EntityApplication.setId(-6747715503667614808l);
            _returnVal1EntityApplication.setName("Name-1403860903");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1EntityApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1EntityApplication.getRoles().addAll(_returnVal1EntityApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1EntityApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1EntityApplication.getUsers().addAll(_returnVal1EntityApplicationUsers);
            _returnVal1Entity.setApplication(_returnVal1EntityApplication);
            _returnVal1Entity.setId(-2703603557922756977l);
            _returnVal1Entity.setName("Name-1276829942");
            _returnVal1Entity.setSync(false);
            _returnVal1.setEntity(_returnVal1Entity);
            _returnVal1.setId(2465452407072041937l);
            uy.com.group05.baascore.sl.services.soap.OperationDTO _returnVal1Operation = new uy.com.group05.baascore.sl.services.soap.OperationDTO();
            _returnVal1Operation.setId(4724347106484919144l);
            _returnVal1Operation.setName("Name-1320798869");
            _returnVal1.setOperation(_returnVal1Operation);
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1Role = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1RoleApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1RoleApplication.setApiClientId("ApiClientId-1531153003");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1RoleApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1RoleApplication.getClients().addAll(_returnVal1RoleApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1RoleApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1RoleApplication.getEntities().addAll(_returnVal1RoleApplicationEntities);
            _returnVal1RoleApplication.setId(-4478685623493239505l);
            _returnVal1RoleApplication.setName("Name2112149685");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1RoleApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1RoleApplication.getRoles().addAll(_returnVal1RoleApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1RoleApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1RoleApplication.getUsers().addAll(_returnVal1RoleApplicationUsers);
            _returnVal1Role.setApplication(_returnVal1RoleApplication);
            _returnVal1Role.setId(1039697214601140533l);
            _returnVal1Role.setName("Name-1607278930");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1RolePermissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnVal1Role.getPermissions().addAll(_returnVal1RolePermissions);
            _returnVal1.setRole(_returnVal1Role);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RoleNotFoundException_Exception("RoleNotFoundException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsApplication(java.lang.String  nombreApp )*
     */
    public boolean existsApplication(java.lang.String nombreApp) { 
        LOG.info("Executing operation existsApplication");
        System.out.println(nombreApp);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsRoleApplication(long  idApp ,)java.lang.String  nomRole )*
     */
    public boolean existsRoleApplication(long idApp,java.lang.String nomRole) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsRoleApplication");
        System.out.println(idApp);
        System.out.println(nomRole);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsPushChannelApplication(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public boolean existsPushChannelApplication(long idApp,java.lang.String nombreCanal) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsPushChannelApplication");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#unassignUserFromApplication(long  idApp ,)long  idUser )*
     */
    public boolean unassignUserFromApplication(long idApp,long idUser) throws AppNotRegisteredException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation unassignUserFromApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editEntityApplication(long  idApp ,)long  idUser ,)java.lang.String  nomEntity ,)boolean  sync )*
     */
    public long editEntityApplication(long idApp,long idUser,java.lang.String nomEntity,boolean sync) throws EntityAlreadyRegisteredException_Exception , EntityCollectionAlreadyExistsException_Exception , InvalidNameException_Exception , UserCantAccessAppException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editEntityApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        System.out.println(nomEntity);
        System.out.println(sync);
        try {
            long _return = -8823339806391432397l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityAlreadyRegisteredException_Exception("EntityAlreadyRegisteredException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserCantAccessAppException_Exception("UserCantAccessAppException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

}
