
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uy.com.group05.baascore.sl.services.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-10-21T19:59:15.542-02:00
 * Generated source version: 2.4.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ApplicationServices",
                      portName = "ApplicationServicesPort",
                      targetNamespace = "http://impl.services.sl.baascore.group05.com.uy/",
                      wsdlLocation = "http://localhost:8080/baas-core/ApplicationServices?wsdl",
                      endpointInterface = "uy.com.group05.baascore.sl.services.soap.ApplicationServices")
                      
public class ApplicationServicesImpl implements ApplicationServices {

    private static final Logger LOG = Logger.getLogger(ApplicationServicesImpl.class.getName());

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#addPushChannelToApplication(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public long addPushChannelToApplication(long idApp,java.lang.String nombreCanal) throws PushChanAlreadyRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation addPushChannelToApplication");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            long _return = -7295785489022623405l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanAlreadyRegisteredException_Exception("PushChanAlreadyRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#createApplication(long  idUser ,)java.lang.String  nombreApp ,)java.util.List<java.lang.String>  rolStr ,)java.util.List<java.lang.String>  entidadStr )*
     */
    public long createApplication(long idUser,java.lang.String nombreApp,java.util.List<java.lang.String> rolStr,java.util.List<java.lang.String> entidadStr) throws NombreAppAlreadyRegisteredException_Exception , MongoDBAlreadyExistsException_Exception , EntityCollectionAlreadyExistsException_Exception , InvalidNameException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation createApplication");
        System.out.println(idUser);
        System.out.println(nombreApp);
        System.out.println(rolStr);
        System.out.println(entidadStr);
        try {
            long _return = 3200002282820692944l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NombreAppAlreadyRegisteredException_Exception("NombreAppAlreadyRegisteredException...");
        //throw new MongoDBAlreadyExistsException_Exception("MongoDBAlreadyExistsException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editApplication(java.lang.String  nombreApp ,)java.util.List<java.lang.String>  rolStr ,)java.util.List<java.lang.String>  entidadStr )*
     */
    public long editApplication(java.lang.String nombreApp,java.util.List<java.lang.String> rolStr,java.util.List<java.lang.String> entidadStr) throws MongoDBAlreadyExistsException_Exception , EntityCollectionAlreadyExistsException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editApplication");
        System.out.println(nombreApp);
        System.out.println(rolStr);
        System.out.println(entidadStr);
        try {
            long _return = -1993681719286569161l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new MongoDBAlreadyExistsException_Exception("MongoDBAlreadyExistsException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#removePushChannelFromApplication(long  idApp ,)long  idCanal )*
     */
    public long removePushChannelFromApplication(long idApp,long idCanal) throws PushChanNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation removePushChannelFromApplication");
        System.out.println(idApp);
        System.out.println(idCanal);
        try {
            long _return = -8000576244765161025l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PushChanNotRegisteredException_Exception("PushChanNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#listApplications(long  idUser )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO> listApplications(long idUser) throws UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation listApplications");
        System.out.println(idUser);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleApplicationDTO();
            _returnVal1.setApiClientId("ApiClientId-2040836813");
            _returnVal1.setId(-1653814439685564822l);
            _returnVal1.setName("Name-468658753");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getPermissionsForEntity(long  appId ,)long  entityId )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> getPermissionsForEntity(long appId,long entityId) throws EntityCollectionNotRegisteredException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPermissionsForEntity");
        System.out.println(appId);
        System.out.println(entityId);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            uy.com.group05.baascore.sl.services.soap.PermissionDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.PermissionDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-548544426");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-2669343847740372661l);
            _returnVal1Application.setName("Name397899107");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1Entity = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1EntityApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1EntityApplication.setApiClientId("ApiClientId1763598036");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1EntityApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1EntityApplication.getClients().addAll(_returnVal1EntityApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1EntityApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1EntityApplication.getEntities().addAll(_returnVal1EntityApplicationEntities);
            _returnVal1EntityApplication.setId(-768881593479403295l);
            _returnVal1EntityApplication.setName("Name1772797012");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1EntityApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1EntityApplication.getRoles().addAll(_returnVal1EntityApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1EntityApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1EntityApplication.getUsers().addAll(_returnVal1EntityApplicationUsers);
            _returnVal1Entity.setApplication(_returnVal1EntityApplication);
            _returnVal1Entity.setId(4387948158183062452l);
            _returnVal1Entity.setName("Name1679155493");
            _returnVal1.setEntity(_returnVal1Entity);
            _returnVal1.setId(3109296153400026278l);
            uy.com.group05.baascore.sl.services.soap.OperationDTO _returnVal1Operation = new uy.com.group05.baascore.sl.services.soap.OperationDTO();
            _returnVal1Operation.setId(5380517059006179899l);
            _returnVal1Operation.setName("Name2076621529");
            _returnVal1.setOperation(_returnVal1Operation);
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1Role = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1RoleApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1RoleApplication.setApiClientId("ApiClientId952587209");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1RoleApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1RoleApplication.getClients().addAll(_returnVal1RoleApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1RoleApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1RoleApplication.getEntities().addAll(_returnVal1RoleApplicationEntities);
            _returnVal1RoleApplication.setId(-112028316903917357l);
            _returnVal1RoleApplication.setName("Name113302300");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1RoleApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1RoleApplication.getRoles().addAll(_returnVal1RoleApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1RoleApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1RoleApplication.getUsers().addAll(_returnVal1RoleApplicationUsers);
            _returnVal1Role.setApplication(_returnVal1RoleApplication);
            _returnVal1Role.setId(-5216725629719764241l);
            _returnVal1Role.setName("Name-1681993519");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1RolePermissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnVal1Role.getPermissions().addAll(_returnVal1RolePermissions);
            _returnVal1.setRole(_returnVal1Role);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityCollectionNotRegisteredException_Exception("EntityCollectionNotRegisteredException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getPushChannelsApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.PushChannelDTO> getPushChannelsApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getPushChannelsApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.PushChannelDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PushChannelDTO>();
            uy.com.group05.baascore.sl.services.soap.PushChannelDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.PushChannelDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId459009647");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-6467787977960026739l);
            _returnVal1Application.setName("Name-1750688208");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1Clients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1ClientsVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1ClientsVal1.setAppName("AppName59629840");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1ClientsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1ClientsVal1Application.setApiClientId("ApiClientId2000232565");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ClientsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1ClientsVal1Application.getClients().addAll(_returnVal1ClientsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ClientsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1ClientsVal1Application.getEntities().addAll(_returnVal1ClientsVal1ApplicationEntities);
            _returnVal1ClientsVal1Application.setId(5526920525308229667l);
            _returnVal1ClientsVal1Application.setName("Name-1118970742");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ClientsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1ClientsVal1Application.getRoles().addAll(_returnVal1ClientsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ClientsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1ClientsVal1Application.getUsers().addAll(_returnVal1ClientsVal1ApplicationUsers);
            _returnVal1ClientsVal1.setApplication(_returnVal1ClientsVal1Application);
            _returnVal1ClientsVal1.setEmail("Email526761864");
            _returnVal1ClientsVal1.setId(7482353111437095549l);
            _returnVal1ClientsVal1.setLastname("Lastname-496056502");
            _returnVal1ClientsVal1.setName("Name285590407");
            _returnVal1ClientsVal1.setPassword("Password-103279463");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1ClientsVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            _returnVal1ClientsVal1.getRoles().addAll(_returnVal1ClientsVal1Roles);
            _returnVal1Clients.add(_returnVal1ClientsVal1);
            _returnVal1.getClients().addAll(_returnVal1Clients);
            _returnVal1.setId(-3531348426624489103l);
            _returnVal1.setName("Name561477458");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editRoleApplication(long  idApp ,)long  idUser ,)java.lang.String  nomRole )*
     */
    public long editRoleApplication(long idApp,long idUser,java.lang.String nomRole) throws RoleAlreadyRegisteredException_Exception , InvalidNameException_Exception , UserCantAccessAppException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editRoleApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        System.out.println(nomRole);
        try {
            long _return = -8508147039158160675l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RoleAlreadyRegisteredException_Exception("RoleAlreadyRegisteredException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserCantAccessAppException_Exception("UserCantAccessAppException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getEntitiesApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> getEntitiesApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getEntitiesApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId-609678613");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-8303971446375460618l);
            _returnVal1Application.setName("Name-1113013341");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setId(244213348018658683l);
            _returnVal1.setName("Name-778579677");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getClientsApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> getClientsApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getClientsApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnVal1.setAppName("AppName738169048");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId1361432488");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-7136004352439385146l);
            _returnVal1Application.setName("Name1446341890");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setEmail("Email-1508965915");
            _returnVal1.setId(8479306452804106987l);
            _returnVal1.setLastname("Lastname-1657496868");
            _returnVal1.setName("Name-1497326003");
            _returnVal1.setPassword("Password363070151");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO _returnVal1RolesVal1 = new uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO();
            _returnVal1RolesVal1.setId(5804620926479135356l);
            _returnVal1RolesVal1.setName("Name-95798619");
            _returnVal1Roles.add(_returnVal1RolesVal1);
            _returnVal1.getRoles().addAll(_returnVal1Roles);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getRolesApplication(long  idApp )*
     */
    public java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> getRolesApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getRolesApplication");
        System.out.println(idApp);
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _return = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1 = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1Application.setApiClientId("ApiClientId1943122892");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1Application.getClients().addAll(_returnVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1Application.getEntities().addAll(_returnVal1ApplicationEntities);
            _returnVal1Application.setId(-8216063064508451657l);
            _returnVal1Application.setName("Name356479797");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1Application.getRoles().addAll(_returnVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1Application.getUsers().addAll(_returnVal1ApplicationUsers);
            _returnVal1.setApplication(_returnVal1Application);
            _returnVal1.setId(-369574040924067781l);
            _returnVal1.setName("Name-557371196");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1Permissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            uy.com.group05.baascore.sl.services.soap.PermissionDTO _returnVal1PermissionsVal1 = new uy.com.group05.baascore.sl.services.soap.PermissionDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1Application.setApiClientId("ApiClientId56183192");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1Application.getClients().addAll(_returnVal1PermissionsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1Application.getEntities().addAll(_returnVal1PermissionsVal1ApplicationEntities);
            _returnVal1PermissionsVal1Application.setId(-6808582484010527399l);
            _returnVal1PermissionsVal1Application.setName("Name-700243938");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1Application.getRoles().addAll(_returnVal1PermissionsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1Application.getUsers().addAll(_returnVal1PermissionsVal1ApplicationUsers);
            _returnVal1PermissionsVal1.setApplication(_returnVal1PermissionsVal1Application);
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnVal1PermissionsVal1Entity = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1EntityApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1EntityApplication.setApiClientId("ApiClientId-2050089772");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1EntityApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1EntityApplication.getClients().addAll(_returnVal1PermissionsVal1EntityApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1EntityApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1EntityApplication.getEntities().addAll(_returnVal1PermissionsVal1EntityApplicationEntities);
            _returnVal1PermissionsVal1EntityApplication.setId(-1636692611765182110l);
            _returnVal1PermissionsVal1EntityApplication.setName("Name-597697361");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1EntityApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1EntityApplication.getRoles().addAll(_returnVal1PermissionsVal1EntityApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1EntityApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1EntityApplication.getUsers().addAll(_returnVal1PermissionsVal1EntityApplicationUsers);
            _returnVal1PermissionsVal1Entity.setApplication(_returnVal1PermissionsVal1EntityApplication);
            _returnVal1PermissionsVal1Entity.setId(-6077450836088544029l);
            _returnVal1PermissionsVal1Entity.setName("Name604027988");
            _returnVal1PermissionsVal1.setEntity(_returnVal1PermissionsVal1Entity);
            _returnVal1PermissionsVal1.setId(6995731971030051374l);
            uy.com.group05.baascore.sl.services.soap.OperationDTO _returnVal1PermissionsVal1Operation = new uy.com.group05.baascore.sl.services.soap.OperationDTO();
            _returnVal1PermissionsVal1Operation.setId(4779749721113605374l);
            _returnVal1PermissionsVal1Operation.setName("Name698540984");
            _returnVal1PermissionsVal1.setOperation(_returnVal1PermissionsVal1Operation);
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnVal1PermissionsVal1Role = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnVal1PermissionsVal1RoleApplication = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnVal1PermissionsVal1RoleApplication.setApiClientId("ApiClientId-1338908775");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnVal1PermissionsVal1RoleApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnVal1PermissionsVal1RoleApplication.getClients().addAll(_returnVal1PermissionsVal1RoleApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnVal1PermissionsVal1RoleApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnVal1PermissionsVal1RoleApplication.getEntities().addAll(_returnVal1PermissionsVal1RoleApplicationEntities);
            _returnVal1PermissionsVal1RoleApplication.setId(160480192464800503l);
            _returnVal1PermissionsVal1RoleApplication.setName("Name-1155306794");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnVal1PermissionsVal1RoleApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnVal1PermissionsVal1RoleApplication.getRoles().addAll(_returnVal1PermissionsVal1RoleApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnVal1PermissionsVal1RoleApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnVal1PermissionsVal1RoleApplication.getUsers().addAll(_returnVal1PermissionsVal1RoleApplicationUsers);
            _returnVal1PermissionsVal1Role.setApplication(_returnVal1PermissionsVal1RoleApplication);
            _returnVal1PermissionsVal1Role.setId(7373141756700566003l);
            _returnVal1PermissionsVal1Role.setName("Name1946676177");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnVal1PermissionsVal1RolePermissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnVal1PermissionsVal1Role.getPermissions().addAll(_returnVal1PermissionsVal1RolePermissions);
            _returnVal1PermissionsVal1.setRole(_returnVal1PermissionsVal1Role);
            _returnVal1Permissions.add(_returnVal1PermissionsVal1);
            _returnVal1.getPermissions().addAll(_returnVal1Permissions);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#assignUserToApplication(long  idApp ,)long  idUser )*
     */
    public boolean assignUserToApplication(long idApp,long idUser) throws AppNotRegisteredException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation assignUserToApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#getApplication(long  idApp )*
     */
    public uy.com.group05.baascore.sl.services.soap.ApplicationDTO getApplication(long idApp) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation getApplication");
        System.out.println(idApp);
        try {
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _return = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _return.setApiClientId("ApiClientId-2114064775");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            uy.com.group05.baascore.sl.services.soap.ClientDTO _returnClientsVal1 = new uy.com.group05.baascore.sl.services.soap.ClientDTO();
            _returnClientsVal1.setAppName("AppName-1164279958");
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnClientsVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnClientsVal1Application.setApiClientId("ApiClientId1074270095");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnClientsVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnClientsVal1Application.getClients().addAll(_returnClientsVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnClientsVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnClientsVal1Application.getEntities().addAll(_returnClientsVal1ApplicationEntities);
            _returnClientsVal1Application.setId(-1599605241091066354l);
            _returnClientsVal1Application.setName("Name28817951");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnClientsVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnClientsVal1Application.getRoles().addAll(_returnClientsVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnClientsVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnClientsVal1Application.getUsers().addAll(_returnClientsVal1ApplicationUsers);
            _returnClientsVal1.setApplication(_returnClientsVal1Application);
            _returnClientsVal1.setEmail("Email-550754221");
            _returnClientsVal1.setId(7888062714620936242l);
            _returnClientsVal1.setLastname("Lastname-1724143659");
            _returnClientsVal1.setName("Name-1153705637");
            _returnClientsVal1.setPassword("Password1647055219");
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO> _returnClientsVal1Roles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimpleRoleDTO>();
            _returnClientsVal1.getRoles().addAll(_returnClientsVal1Roles);
            _returnClients.add(_returnClientsVal1);
            _return.getClients().addAll(_returnClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            uy.com.group05.baascore.sl.services.soap.EntityDTO _returnEntitiesVal1 = new uy.com.group05.baascore.sl.services.soap.EntityDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnEntitiesVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnEntitiesVal1Application.setApiClientId("ApiClientId1149360132");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnEntitiesVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnEntitiesVal1Application.getClients().addAll(_returnEntitiesVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnEntitiesVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnEntitiesVal1Application.getEntities().addAll(_returnEntitiesVal1ApplicationEntities);
            _returnEntitiesVal1Application.setId(-6358483711251044050l);
            _returnEntitiesVal1Application.setName("Name-2140643738");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnEntitiesVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnEntitiesVal1Application.getRoles().addAll(_returnEntitiesVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnEntitiesVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnEntitiesVal1Application.getUsers().addAll(_returnEntitiesVal1ApplicationUsers);
            _returnEntitiesVal1.setApplication(_returnEntitiesVal1Application);
            _returnEntitiesVal1.setId(5812443974787812937l);
            _returnEntitiesVal1.setName("Name1293918993");
            _returnEntities.add(_returnEntitiesVal1);
            _return.getEntities().addAll(_returnEntities);
            _return.setId(-7793347967593893484l);
            _return.setName("Name1409622542");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            uy.com.group05.baascore.sl.services.soap.RoleDTO _returnRolesVal1 = new uy.com.group05.baascore.sl.services.soap.RoleDTO();
            uy.com.group05.baascore.sl.services.soap.ApplicationDTO _returnRolesVal1Application = new uy.com.group05.baascore.sl.services.soap.ApplicationDTO();
            _returnRolesVal1Application.setApiClientId("ApiClientId245144512");
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _returnRolesVal1ApplicationClients = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.ClientDTO>();
            _returnRolesVal1Application.getClients().addAll(_returnRolesVal1ApplicationClients);
            java.util.List<uy.com.group05.baascore.sl.services.soap.EntityDTO> _returnRolesVal1ApplicationEntities = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.EntityDTO>();
            _returnRolesVal1Application.getEntities().addAll(_returnRolesVal1ApplicationEntities);
            _returnRolesVal1Application.setId(-1455446653102811917l);
            _returnRolesVal1Application.setName("Name422689068");
            java.util.List<uy.com.group05.baascore.sl.services.soap.RoleDTO> _returnRolesVal1ApplicationRoles = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.RoleDTO>();
            _returnRolesVal1Application.getRoles().addAll(_returnRolesVal1ApplicationRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnRolesVal1ApplicationUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            _returnRolesVal1Application.getUsers().addAll(_returnRolesVal1ApplicationUsers);
            _returnRolesVal1.setApplication(_returnRolesVal1Application);
            _returnRolesVal1.setId(-2099084959968253785l);
            _returnRolesVal1.setName("Name-1916764632");
            java.util.List<uy.com.group05.baascore.sl.services.soap.PermissionDTO> _returnRolesVal1Permissions = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.PermissionDTO>();
            _returnRolesVal1.getPermissions().addAll(_returnRolesVal1Permissions);
            _returnRoles.add(_returnRolesVal1);
            _return.getRoles().addAll(_returnRoles);
            java.util.List<uy.com.group05.baascore.sl.services.soap.UserDTO> _returnUsers = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.UserDTO>();
            uy.com.group05.baascore.sl.services.soap.UserDTO _returnUsersVal1 = new uy.com.group05.baascore.sl.services.soap.UserDTO();
            _returnUsersVal1.setEmail("Email2142646208");
            _returnUsersVal1.setId(2379799031626821933l);
            _returnUsersVal1.setLastname("Lastname-1383576979");
            _returnUsersVal1.setLoggedIn(false);
            _returnUsersVal1.setName("Name1276094801");
            _returnUsers.add(_returnUsersVal1);
            _return.getUsers().addAll(_returnUsers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsApplication(java.lang.String  nombreApp )*
     */
    public boolean existsApplication(java.lang.String nombreApp) { 
        LOG.info("Executing operation existsApplication");
        System.out.println(nombreApp);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsEntityApplication(long  idApp ,)java.lang.String  nomEntity )*
     */
    public boolean existsEntityApplication(long idApp,java.lang.String nomEntity) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsEntityApplication");
        System.out.println(idApp);
        System.out.println(nomEntity);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsRoleApplication(long  idApp ,)java.lang.String  nomRole )*
     */
    public boolean existsRoleApplication(long idApp,java.lang.String nomRole) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsRoleApplication");
        System.out.println(idApp);
        System.out.println(nomRole);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#existsPushChannelApplication(long  idApp ,)java.lang.String  nombreCanal )*
     */
    public boolean existsPushChannelApplication(long idApp,java.lang.String nombreCanal) throws AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation existsPushChannelApplication");
        System.out.println(idApp);
        System.out.println(nombreCanal);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#unassignUserFromApplication(long  idApp ,)long  idUser )*
     */
    public boolean unassignUserFromApplication(long idApp,long idUser) throws AppNotRegisteredException_Exception , UserNotRegisteredException_Exception    { 
        LOG.info("Executing operation unassignUserFromApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
        //throw new UserNotRegisteredException_Exception("UserNotRegisteredException...");
    }

    /* (non-Javadoc)
     * @see uy.com.group05.baascore.sl.services.soap.ApplicationServices#editEntityApplication(long  idApp ,)long  idUser ,)java.lang.String  nomEntity )*
     */
    public long editEntityApplication(long idApp,long idUser,java.lang.String nomEntity) throws EntityAlreadyRegisteredException_Exception , EntityCollectionAlreadyExistsException_Exception , InvalidNameException_Exception , UserCantAccessAppException_Exception , AppNotRegisteredException_Exception    { 
        LOG.info("Executing operation editEntityApplication");
        System.out.println(idApp);
        System.out.println(idUser);
        System.out.println(nomEntity);
        try {
            long _return = 6490255122455612209l;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EntityAlreadyRegisteredException_Exception("EntityAlreadyRegisteredException...");
        //throw new EntityCollectionAlreadyExistsException_Exception("EntityCollectionAlreadyExistsException...");
        //throw new InvalidNameException_Exception("InvalidNameException...");
        //throw new UserCantAccessAppException_Exception("UserCantAccessAppException...");
        //throw new AppNotRegisteredException_Exception("AppNotRegisteredException...");
    }

}
