
package uy.com.group05.baascore.sl.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-25T01:54:56.251-02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "EntityCollectionNotRegisteredException", targetNamespace = "http://soap.services.sl.baascore.group05.com.uy/")
public class EntityCollectionNotRegisteredException_Exception extends Exception {
    
    private uy.com.group05.baascore.sl.services.soap.EntityCollectionNotRegisteredException entityCollectionNotRegisteredException;

    public EntityCollectionNotRegisteredException_Exception() {
        super();
    }
    
    public EntityCollectionNotRegisteredException_Exception(String message) {
        super(message);
    }
    
    public EntityCollectionNotRegisteredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EntityCollectionNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.EntityCollectionNotRegisteredException entityCollectionNotRegisteredException) {
        super(message);
        this.entityCollectionNotRegisteredException = entityCollectionNotRegisteredException;
    }

    public EntityCollectionNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.EntityCollectionNotRegisteredException entityCollectionNotRegisteredException, Throwable cause) {
        super(message, cause);
        this.entityCollectionNotRegisteredException = entityCollectionNotRegisteredException;
    }

    public uy.com.group05.baascore.sl.services.soap.EntityCollectionNotRegisteredException getFaultInfo() {
        return this.entityCollectionNotRegisteredException;
    }
}
