
package uy.com.group05.baascore.sl.services.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import uy.com.group05.baascore.sl.services.impl.PushServices;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-10-27T17:42:53.415-02:00
 * Generated source version: 2.4.6
 * 
 */
public final class PushChannelServices_PushServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.services.sl.baascore.group05.com.uy/", "PushServices");

    private PushChannelServices_PushServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PushServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PushServices ss = new PushServices(wsdlURL, SERVICE_NAME);
        PushChannelServices port = ss.getPushServicesPort();  
        
        {
        System.out.println("Invoking getPushChannelsOfApplication...");
        long _getPushChannelsOfApplication_arg0 = 4298542929472139807l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelDTO> _getPushChannelsOfApplication__return = port.getPushChannelsOfApplication(_getPushChannelsOfApplication_arg0);
            System.out.println("getPushChannelsOfApplication.result=" + _getPushChannelsOfApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignEntityToPushChannel...");
        long _assignEntityToPushChannel_idApp = -3493844845983298402l;
        long _assignEntityToPushChannel_idCanal = 390664221738140374l;
        long _assignEntityToPushChannel_idEntity = 436134693597703726l;
        try {
            boolean _assignEntityToPushChannel__return = port.assignEntityToPushChannel(_assignEntityToPushChannel_idApp, _assignEntityToPushChannel_idCanal, _assignEntityToPushChannel_idEntity);
            System.out.println("assignEntityToPushChannel.result=" + _assignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendNotificationToPushChannel...");
        long _sendNotificationToPushChannel_idApp = 1462549220128384405l;
        long _sendNotificationToPushChannel_idCanal = 4376512357525627328l;
        java.lang.String _sendNotificationToPushChannel_mensaje = "_sendNotificationToPushChannel_mensaje1800806906";
        try {
            boolean _sendNotificationToPushChannel__return = port.sendNotificationToPushChannel(_sendNotificationToPushChannel_idApp, _sendNotificationToPushChannel_idCanal, _sendNotificationToPushChannel_mensaje);
            System.out.println("sendNotificationToPushChannel.result=" + _sendNotificationToPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignClientToPushChannel...");
        long _assignClientToPushChannel_idApp = -2382165576549319459l;
        long _assignClientToPushChannel_idCanal = 7585690839482263717l;
        long _assignClientToPushChannel_idCliente = 5586694474850272801l;
        try {
            boolean _assignClientToPushChannel__return = port.assignClientToPushChannel(_assignClientToPushChannel_idApp, _assignClientToPushChannel_idCanal, _assignClientToPushChannel_idCliente);
            System.out.println("assignClientToPushChannel.result=" + _assignClientToPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignEntityToPushChannel...");
        long _unassignEntityToPushChannel_idApp = 2957402344992506888l;
        long _unassignEntityToPushChannel_idCanal = -5040723060249282589l;
        long _unassignEntityToPushChannel_idEntity = -977166880480417788l;
        try {
            boolean _unassignEntityToPushChannel__return = port.unassignEntityToPushChannel(_unassignEntityToPushChannel_idApp, _unassignEntityToPushChannel_idCanal, _unassignEntityToPushChannel_idEntity);
            System.out.println("unassignEntityToPushChannel.result=" + _unassignEntityToPushChannel__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking savePushChannelEntities...");
        long _savePushChannelEntities_idApp = -2859813033506382737l;
        long _savePushChannelEntities_idCanal = 1092912298817549737l;
        java.util.List<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO> _savePushChannelEntities_entity = new java.util.ArrayList<uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO>();
        uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO _savePushChannelEntities_entityVal1 = new uy.com.group05.baascore.sl.services.soap.SimplePushChannelEntityDTO();
        _savePushChannelEntities_entityVal1.setAssociated(false);
        _savePushChannelEntities_entityVal1.setId(-6261635428954857819l);
        _savePushChannelEntities_entityVal1.setName("Name-1729391344");
        _savePushChannelEntities_entity.add(_savePushChannelEntities_entityVal1);
        try {
            boolean _savePushChannelEntities__return = port.savePushChannelEntities(_savePushChannelEntities_idApp, _savePushChannelEntities_idCanal, _savePushChannelEntities_entity);
            System.out.println("savePushChannelEntities.result=" + _savePushChannelEntities__return);

        } catch (EntityNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: EntityNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createPushChannel...");
        long _createPushChannel_idApp = -2956019260849908864l;
        java.lang.String _createPushChannel_nombreCanal = "_createPushChannel_nombreCanal-1858538379";
        try {
            long _createPushChannel__return = port.createPushChannel(_createPushChannel_idApp, _createPushChannel_nombreCanal);
            System.out.println("createPushChannel.result=" + _createPushChannel__return);

        } catch (PushChanAlreadyRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanAlreadyRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unassignClientFromPushChannel...");
        long _unassignClientFromPushChannel_idApp = 8603309492370608026l;
        long _unassignClientFromPushChannel_idCanal = -5983786184129527122l;
        long _unassignClientFromPushChannel_idCliente = 7994729692000084391l;
        try {
            boolean _unassignClientFromPushChannel__return = port.unassignClientFromPushChannel(_unassignClientFromPushChannel_idApp, _unassignClientFromPushChannel_idCanal, _unassignClientFromPushChannel_idCliente);
            System.out.println("unassignClientFromPushChannel.result=" + _unassignClientFromPushChannel__return);

        } catch (ClientNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: ClientNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClientsFromPushChannel...");
        long _getClientsFromPushChannel_idApp = 4008117431607648478l;
        long _getClientsFromPushChannel_idCanal = 1250691586439313096l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.ClientDTO> _getClientsFromPushChannel__return = port.getClientsFromPushChannel(_getClientsFromPushChannel_idApp, _getClientsFromPushChannel_idCanal);
            System.out.println("getClientsFromPushChannel.result=" + _getClientsFromPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannelApplication...");
        long _existsPushChannelApplication_idApp = 4220150502235924595l;
        java.lang.String _existsPushChannelApplication_nombreCanal = "_existsPushChannelApplication_nombreCanal1576409874";
        try {
            boolean _existsPushChannelApplication__return = port.existsPushChannelApplication(_existsPushChannelApplication_idApp, _existsPushChannelApplication_nombreCanal);
            System.out.println("existsPushChannelApplication.result=" + _existsPushChannelApplication__return);

        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEntitiesAssociatedWithPushChannel...");
        long _getEntitiesAssociatedWithPushChannel_idApp = 3397420316749384659l;
        long _getEntitiesAssociatedWithPushChannel_idCanal = -6856932047740579902l;
        try {
            java.util.List<uy.com.group05.baascore.sl.services.soap.SimpleEntityDTO> _getEntitiesAssociatedWithPushChannel__return = port.getEntitiesAssociatedWithPushChannel(_getEntitiesAssociatedWithPushChannel_idApp, _getEntitiesAssociatedWithPushChannel_idCanal);
            System.out.println("getEntitiesAssociatedWithPushChannel.result=" + _getEntitiesAssociatedWithPushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deletePushChannel...");
        long _deletePushChannel_idApp = 2695785068508292718l;
        long _deletePushChannel_idCanal = 2991292338736719371l;
        try {
            long _deletePushChannel__return = port.deletePushChannel(_deletePushChannel_idApp, _deletePushChannel_idCanal);
            System.out.println("deletePushChannel.result=" + _deletePushChannel__return);

        } catch (PushChanNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: PushChanNotRegisteredException has occurred.");
            System.out.println(e.toString());
        } catch (AppNotRegisteredException_Exception e) { 
            System.out.println("Expected exception: AppNotRegisteredException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking existsPushChannel...");
        long _existsPushChannel_idCanal = -8947661415288770326l;
        boolean _existsPushChannel__return = port.existsPushChannel(_existsPushChannel_idCanal);
        System.out.println("existsPushChannel.result=" + _existsPushChannel__return);


        }

        System.exit(0);
    }

}
