
package uy.com.group05.baascore.sl.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-10-27T16:08:11.485-02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "PushChanNotRegisteredException", targetNamespace = "http://soap.services.sl.baascore.group05.com.uy/")
public class PushChanNotRegisteredException_Exception extends Exception {
    
    private uy.com.group05.baascore.sl.services.soap.PushChanNotRegisteredException pushChanNotRegisteredException;

    public PushChanNotRegisteredException_Exception() {
        super();
    }
    
    public PushChanNotRegisteredException_Exception(String message) {
        super(message);
    }
    
    public PushChanNotRegisteredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PushChanNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.PushChanNotRegisteredException pushChanNotRegisteredException) {
        super(message);
        this.pushChanNotRegisteredException = pushChanNotRegisteredException;
    }

    public PushChanNotRegisteredException_Exception(String message, uy.com.group05.baascore.sl.services.soap.PushChanNotRegisteredException pushChanNotRegisteredException, Throwable cause) {
        super(message, cause);
        this.pushChanNotRegisteredException = pushChanNotRegisteredException;
    }

    public uy.com.group05.baascore.sl.services.soap.PushChanNotRegisteredException getFaultInfo() {
        return this.pushChanNotRegisteredException;
    }
}
